### ISSUE TITLE
The git clone command in Page 3 doesn't work

### ISSUE THREAD

**Issue by cyanglaz** [FirebaseExtended/codelab-friendlyeats-flutter#1]
https://codelabs.developers.google.com/codelabs/friendlyeats-flutter/index.html?index=..%2F..index#2

The command says `git clone git@github.com:FirebaseExtended/codelab-friendlyeats-flutter friendlyeats-flutter`
It should probably be something like `git clone git@github.com:FirebaseExtended/codelab-friendlyeats-flutter.git friendlyeats-flutter`

**Comment by ditman** [comment]
The user reported that they were able to clone from an https URL, they probably don't have their SSH key setup in Github. I'll fix the link to be a HTTPS one, instead of SSH.

**Comment by ditman** [comment]
Bad clone:
![bad](https://user-images.githubusercontent.com/1255594/85888026-a5f0ed80-b79d-11ea-809c-cd9e3f1d28ca.png)

Good clone:
![good](https://user-images.githubusercontent.com/1255594/85888040-abe6ce80-b79d-11ea-9873-89e3ba2ed9de.png)

**Comment by cyanglaz** [comment]
I think even the ssh would be something like git@github.com:FirebaseExtended/codelab-friendlyeats-flutter.git`?

**Comment by ditman** [comment]
I just tested without `.git` again and it worked on my machine 🤷‍♂️

Maybe different versions of git?

**Comment by cyanglaz** [comment]
ah. Not sure. I have always used .git.
Anyway, making it to be `https` should be the way to do it.

**Comment by ditman** [comment]
Ahhh ok, I used a git URL that requires the user to be authenticated. I'll use the one where people can just clone anonymously!

https://superuser.com/a/557904

**Comment by puf** [comment]
Oh dear... does this mean I have to redo-record the video that I recorded for this codelab? :)

**Comment by ditman** [comment]
@puf no, the change is minimal. If people are following the codelab, they'll just see a slightly different clone URL in that step. I don't think you need to re-record anything?

**Comment by ditman** [comment]
(Changed the URL to https, and published the codelab again!)
