### ISSUE TITLE
Firebase Hosting Deploy error

### ISSUE THREAD

**Issue by edgfowler** [FirebaseExtended/codelab-friendlyeats-flutter#3]
Had to modify firebase.json hosting-predeploy prop to avoid error.

From: 
"**predeploy": "flutter clean; flutter build web",**
To: 
**"predeploy": ["flutter clean", "flutter build web"],**

This works, but I'm not sure if this is the preferred syntax.

Error:
D:\apps\flutter\codelab-friendlyeats>firebase deploy --only hosting

=== Deploying to 'edgfowler-1'...

i  deploying hosting
Running command: flutter clean; flutter build web
Could not find a command named "clean;".

**Comment by ditman** [comment]
@edgfowler can you try the following in your box? `"flutter clean & flutter build web"` ?

That should run both `flutter clean` and `flutter build web`.

(I haven't found any reference about having an array of predeploy commands in the firebase docs! /cc @puf any idea?)

**Comment by mzdm** [comment]
Just tried it and had the same issue.

```
firebase deploy --only hosting

=== Deploying to 'friendlyeats-f6776'...

i  deploying hosting
Running command: flutter clean; flutter build web
Could not find a command named "clean;".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

Error: hosting predeploy error: Command terminated with non-zero exit code64
```

As mentioned above changing it from

`"predeploy": "flutter clean; flutter build web",`
to
`"predeploy": "flutter clean & flutter build web",` or `"predeploy": ["flutter clean", "flutter build web"],`

Fixes the issue.

**Comment by ditman** [comment]
This completely fell through the cracks of my notifications, I'll fix this by EOW. Thanks for reporting @edgfowler  and pinging @mzdm!

**Comment by ditman** [comment]
Thanks for the fix @mzdm! The fix has propagated to the codelab code, so this should work from now on!

**Comment by xpat** [comment]
@ditman Hi again, I'm working on an error related to deploy.  (Too early to tell if it's just me or something in the code.)  The deploy completes without an error: 

xpat@penguin:~/FlutterProjects/codelabs/friendly_flutter$ firebase deploy --only hosting

```
=== Deploying to 'fluttereats'...

i  deploying hosting
Running command: flutter clean & flutter build web
Waiting for another flutter command to release the startup lock...
Deleting build...                                                   15ms
Deleting .dart_tool...                                              12ms
Deleting Generated.xcconfig...                                       4ms
Deleting flutter_export_environment.sh...                            1ms
Deleting .flutter-plugins-dependencies...                            1ms
Deleting .flutter-plugins...                                         0ms
Running "flutter pub get" in friendly_flutter...                    0.7s
Compiling lib/main.dart for the Web...                             50.4s
✔  hosting: Finished running predeploy script.
i  hosting[fluttereats]: beginning deploy...
i  hosting[fluttereats]: found 15 files in build/web
✔  hosting[fluttereats]: file upload complete
i  hosting[fluttereats]: finalizing version...
✔  hosting[fluttereats]: version finalized
i  hosting[fluttereats]: releasing new version...
✔  hosting[fluttereats]: release complete

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/fluttereats/overview
Hosting URL: https://fluttereats.web.app

```

Following the link, I get a blank white screen.  The favicon works.  I get the prompt to install (as a progressive web app).  The app itself fails to show.  Inspector, console output is as follows:

```
Uncaught TypeError: firebase.firestore is not a function
    at Object.ab1 (top_level.dart:125)
    at cloud_firestore_web.dart:27
    at a5J.a (async_patch.dart:315)
    at a5J.$2 (async_patch.dart:340)
    at Object.W (async_patch.dart:245)
    at Object.LD (main.dart:8)
    at js_helper.dart:2813
    at js_helper.dart:2677
    at dartProgram (js_helper.dart:2677)
    at js_helper.dart:2813
```
This happens regardless of whether it's hosted on Firebase or on my own GCP linux server.  It fails for this and for a chat app (London App Brewery) I tried to host on my own server.  [chat.ambientx.dev](https://chat.ambientx.dev)  The error message there is the same.

**Comment by ditman** [comment]
`Uncaught TypeError: firebase.firestore is not a function`

Ah, I suspect this was missing some `<script>` tags in the index.html?

**Comment by xpat** [comment]
@ditman I thought so, too.  But it looks as it's supposed to look, according to my nascent understanding of the FlutterFire docs. 
Could it be missing async or future?  What about the fact that the databaseURL points to a realtime database and is null?

`databaseURL: "https://fluttereats.firebaseio.com",`


I'm getting this error message, too: Could not load content for org-dartlang-sdk:///lib/async/zone.dart (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)

The initialize script contains the same info as the script var firebaseConfig. I included the script and not the reference to it.

` <script src="/__/firebase/init.js"></script>` 

(That same script is accessible at https://<YOUR-PROJECT>.firebaseapp.com/__/firebase/init.js)

Here are the scripts I have in my web/index.html
```
<script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js"></script>

  <!-- done: Add SDKs for Firebase products that you want to use
       (firebase-auth.js, firebase-firestore.js, firebase-analytics.js...)
       https://firebase.google.com/docs/web/setup#available-libraries -->
 <script defer src="https://www.gstatic.com/firebasejs/7.20/firebase-auth.js"></script>
 <script defer src="https://www.gstatic.com/firebasejs/7.20/firebase-firestore.js"></script>
<!--  <script src="/__/firebase/init.js"></script>-->

....

  <script src="main.dart.js" type="application/javascript"></script>

```
@iapicca

**Comment by ditman** [comment]
@xpat try removing the `defer` from the firebasejs scripts. That way the browser will know that they need to be loaded before your main.dart.js loads.

(Where did that defer come from? the Firebase website?)

**Comment by xpat** [comment]
@ditman  You solved it.  Thanks a million for your help.  Of course that worked.  (I can't believe I didn't see it myself, duh, as if async, future, await and defer aren't all essentially synonyms.) The codelab app is on-line at fluttereats.web.app#.  A different app (the London App Brewery chat app) also works at chat.ambientx.dev 

So I'm sold on Firebase -- if not for hosting, then for authentication and storage.  Now that you showed me how to get it I see that I can different options for hosting.  That was important to me, as I didn't want to be locked into Firebase for hosting.

**Comment by xpat** [comment]
@ditman  

> (Where did that defer come from? the Firebase website?)

The defer came from here:  https://firebase.google.com/docs/web/setup
```
Delay loading of Firebase SDKs (from CDN)
You can delay the inclusion of the Firebase SDKs until the entire page has loaded.

Add a defer flag to each script tag for the Firebase SDKs, then defer the initialization of Firebase using a second script, for example:

<script defer src="https://www.gstatic.com/firebasejs/7.20.-/firebase-app.js"></script>

<script defer src="https://www.gstatic.com/firebasejs/7.20.-/firebase-auth.js"></script>
<script defer src="https://www.gstatic.com/firebasejs/7.20.-/firebase-firestore.js"></script>

// ...

<script defer src="./init-firebase.js"></script>
```

It would be helpful to those of us if the main documentation had absolute paths instead of relative paths, or both.  I had to go snooping around to get the full url and that's how I fell onto this.  I wasn't even paying attention to the context -- delay, defer.  I was just happy to finally get something other than 

`<script src="/__/firebase/7.20.-/firebase-app.js></script>  `

**Comment by ditman** [comment]
Oh, I hadn't seen that before!

I think we need to make a note in our setup instructions *not* to use the Defer part of the [documentation](https://firebase.google.com/docs/web/setup#delay-sdks-cdn), that breaks our setup (for Flutter Web, at least!)

In fact, all you need is the "From the CDN" part of [step 3](https://firebase.google.com/docs/web/setup#add-sdks-initialize), pretty much.

**Comment by ditman** [comment]
(PS: Super glad that you liked Firebase! I laughed at the _¡Pinche Poutine!_ restaurant, I'm sure that was not randomly generated :P)

**Comment by xpat** [comment]
> (PS: Super glad that you liked Firebase! I laughed at the _¡Pinche Poutine!_ restaurant, I'm sure that was not randomly generated :P)

¡Pinche Poutine! is my restaurant in Guadalajara (temporarily closed because of the pandemic). I'm learning all this flutter and firebase, etc. in order to make the digital platform for ¡Pinche Poutine! and a new café/resto in the works there called ¡Hola, Lola! Café.  Thanks for noticing!
